version: '3.3'

services:
  intercom:
    container_name: intercom
    image: maven:latest
    volumes:
    - ../intercom:/usr/src/intercom
    - ~/.m2/:/root/.m2
    working_dir: /usr/src/intercom
    command: bash -c "sleep 5 && cd /usr/src/intercom && mvn package && java -jar target/intercom-1.0.jar"
    stdin_open: true
    tty: true
